### ISSUE TITLE
Add new configuration for JBoss EAP 6 + PostgreSQL

### ISSUE THREAD

**Issue by btsatoukzn** [terasolunaorg/terasoluna-gfw-functionaltest#200]
## Description
Add new configuration / profile for JBoss environment with PostgreSQL Database.

**Comment by btsatoukzn** [comment]
Red Hat JBoss Enterprise Application Platform - Version 6.4.0.GA を使用してGFWFunctionalTest 5.0.0.RELEASEを実行すると下記エラーが発生する。

Caused by: java.lang.NoSuchMethodError: javax.persistence.Table.indexes()[Ljavax/persistence/Index;

ここで、ファイル「jboss-deployment-structure.xml」をWEB-INF配下に新規追加して、FunctionalTestを再度実行すると下記エラーが発生する。

■jboss-deployment-structure.xmlの内容
```xml
<jboss-deployment-structure>
	<deployment>
		<!-- Exclusions allow you to prevent the server from automatically adding 
			some dependencies -->
		<exclusions>
			<module name="javaee.api" />
			<module name="javax.persistence.api" />
		</exclusions>
	</deployment>
</jboss-deployment-structure>
```
■エラー内容
```console
15:29:54,420 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-5) MSC000001: Failed to start service jboss.deployment.unit."terasoluna-gfw-functionaltest-web.war".FIRST_MODULE_USE: org.jboss.msc.service.StartException in service jboss.deployment.unit."terasoluna-gfw-functionaltest-web.war".FIRST_MODULE_USE: JBAS018733: deployment "terasoluna-gfw-functionaltest-web.war" のフェーズ FIRST_MODULE_USE の処理に失敗しました。
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:166) [jboss-as-server-7.5.0.Final-redhat-21.jar:7.5.0.Final-redhat-21]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1980) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1913) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_40]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_40]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_40]
Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: JBAS011426: アプリケーションにパッケージされている永続プロバイダー 'org.hibernate.jpa.HibernatePersistenceProvider' をデプロイできませんでした。
	at org.jboss.as.jpa.processor.PersistenceProviderHandler.deploy(PersistenceProviderHandler.java:79)
	at org.jboss.as.jpa.processor.PersistenceBeginInstallProcessor.deploy(PersistenceBeginInstallProcessor.java:45)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:159) [jboss-as-server-7.5.0.Final-redhat-21.jar:7.5.0.Final-redhat-21]
	... 5 more
Caused by: java.lang.ClassCastException: class org.hibernate.jpa.HibernatePersistenceProvider
	at java.lang.Class.asSubclass(Class.java:3404) [rt.jar:1.8.0_40]
	at org.jboss.as.jpa.processor.PersistenceProviderHandler.deploy(PersistenceProviderHandler.java:73)
	... 7 more
```

**Comment by making** [comment]
@btsatoukzn 

Did you refer https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/tree/master/terasoluna-gfw-functionaltest-env/configs/weblogic-oracle ?


Doesn't it require [javax.persistence.spi.PersistenceProvider](https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/blob/master/terasoluna-gfw-functionaltest-env/configs/weblogic-oracle/resources/META-INF/services/javax.persistence.spi.PersistenceProvider) ?

Is excluding `<module name="javaee.api" />` really correct?
