### ISSUE TITLE
Create new profile for JBoss 7 + PostgreSQL 9

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/terasoluna-gfw-functionaltest#507]
## Description
We'll support JBoss EAP 7 + PostgreSQL 9 as new test environment.

## Possible Solutions
Add `jboss7-postgresql` profile.

## Affects Version/s
\-

## Fix Version/s
- [x] 5.3.0

## Issue Links
N/A

**Comment by bttamuratsh** [comment]
プロファイルを作成しローカルで試験中ですが、fullHalfPairsBuilderErrorTest03_01~06がパスできていません。
いずれも全角半角変換の異常系です。

**Comment by kazuki43zoo** [comment]
@bttamuratsh please write by English at the next time !

**Comment by bttamuratsh** [comment]
The following log is the result of fullHalfPairsBuilderErrorTest03_01. 02~06 tests' results are same as this.
```
Tests run: 10, Failures: 6, Errors: 0, Skipped: 0, Time elapsed: 72.47 sec <<< FAILURE!
fullHalfPairsBuilderErrorTest03_01(org.terasoluna.gfw.functionaltest.app.string.FullHalfConverterTest)  Time elapsed: 2.902 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <1L>
     but: was <0L>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.terasoluna.gfw.functionaltest.app.string.FullHalfConverterTest.fullHalfPairsBuilderErrorTest03_01(FullHalfConverterTest.java:150)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:254)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:89)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:193)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```
According to the client log, JdbcTemplate failed to get the event_id, or the id was not recorded.
```
date:2016-12-01 13:17:41	thread:main	X-Track:	level:DEBUG	logger:o.s.jdbc.datasource.DataSourceTransactionManager	message:Acquired Connection [net.sf.log4jdbc.ConnectionSpy@6401d0a0] for JDBC transaction
date:2016-12-01 13:17:41	thread:main	X-Track:	level:INFO 	logger:o.t.gfw.functionaltest.domain.DBLogCleaner      	message:Begin cleanupAll.
date:2016-12-01 13:17:41	thread:main	X-Track:	level:INFO 	logger:o.t.gfw.functionaltest.domain.DBLogCleaner      	message:Begin cleanup. cutoffDate is 'Thu Dec 01 13:17:41 JST 2016'.
date:2016-12-01 13:17:42	thread:main	X-Track:	level:DEBUG	logger:jdbc.sqltiming                                  	message: org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:688)
1. SELECT MAX(event_id) FROM logging_event WHERE timestmp < 1480565861997 {executed in 11 msec}
date:2016-12-01 13:17:42	thread:main	X-Track:	level:INFO 	logger:o.t.gfw.functionaltest.domain.DBLogCleaner      	message:Finished cleanup. Not exists target log.
date:2016-12-01 13:17:42	thread:main	X-Track:	level:INFO 	logger:o.t.gfw.functionaltest.domain.DBLogCleaner      	message:Finished cleanupAll.
date:2016-12-01 13:17:42	thread:main	X-Track:	level:DEBUG	logger:o.s.jdbc.datasource.DataSourceTransactionManager	message:Initiating transaction commit
date:2016-12-01 13:17:42	thread:main	X-Track:	level:DEBUG	logger:o.s.jdbc.datasource.DataSourceTransactionManager	message:Committing JDBC transaction on Connection [net.sf.log4jdbc.ConnectionSpy@6401d0a0]
date:2016-12-01 13:17:42	thread:main	X-Track:	level:DEBUG	logger:o.s.jdbc.datasource.DataSourceTransactionManager	message:Releasing JDBC Connection [net.sf.log4jdbc.ConnectionSpy@6401d0a0] after transaction
date:2016-12-01 13:17:42	thread:main	X-Track:	level:DEBUG	logger:o.s.jdbc.datasource.DataSourceUtils             	message:Returning JDBC Connection to DataSource
date:2016-12-01 13:17:43	thread:main	X-Track:	level:DEBUG	logger:o.s.jdbc.datasource.DataSourceUtils             	message:Fetching JDBC Connection from DataSource
date:2016-12-01 13:17:43	thread:main	X-Track:	level:DEBUG	logger:jdbc.sqltiming                                  	message: org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:688)
2. SELECT COUNT(e.*) FROM logging_event e JOIN logging_event_exception ee ON ee.event_id = e.event_id WHERE e.formatted_message REGEXP 'fullwidth must be 1 length string \(fullwidth = \)' AND ee.I = '0' AND ee.TRACE_LINE REGEXP '..*IllegalArgumentException..*' {executed in 0 msec}
date:2016-12-01 13:17:43	thread:main	X-Track:	level:DEBUG	logger:o.s.jdbc.datasource.DataSourceUtils             	message:Returning JDBC Connection to DataSource
date:2016-12-01 13:17:43	thread:main	X-Track:	level:DEBUG	logger:o.s.jdbc.datasource.DataSourceUtils             	message:Fetching JDBC Connection from DataSource
date:2016-12-01 13:17:43	thread:main	X-Track:	level:DEBUG	logger:jdbc.sqltiming                                  	message: org.springframework.jdbc.core.JdbcTemplate$1QueryStatementCallback.doInStatement(JdbcTemplate.java:454)
3. SELECT * FROM logging_event ORDER BY event_id ASC {executed in 3 msec}
date:2016-12-01 13:17:43	thread:main	X-Track:	level:DEBUG	logger:o.s.jdbc.datasource.DataSourceUtils             	message:Returning JDBC Connection to DataSource
date:2016-12-01 13:17:43	thread:main	X-Track:	level:DEBUG	logger:o.s.jdbc.datasource.DataSourceUtils             	message:Fetching JDBC Connection from DataSource
date:2016-12-01 13:17:43	thread:main	X-Track:	level:DEBUG	logger:jdbc.sqltiming                                  	message: org.springframework.jdbc.core.JdbcTemplate$1QueryStatementCallback.doInStatement(JdbcTemplate.java:454)
4. SELECT * FROM logging_event_property ORDER BY event_id ASC, mapped_key ASC {executed in 1 msec}
date:2016-12-01 13:17:43	thread:main	X-Track:	level:DEBUG	logger:o.s.jdbc.datasource.DataSourceUtils             	message:Returning JDBC Connection to DataSource
date:2016-12-01 13:17:43	thread:main	X-Track:	level:DEBUG	logger:o.s.jdbc.datasource.DataSourceUtils             	message:Fetching JDBC Connection from DataSource
date:2016-12-01 13:17:43	thread:main	X-Track:	level:DEBUG	logger:jdbc.sqltiming                                  	message: org.springframework.jdbc.core.JdbcTemplate$1QueryStatementCallback.doInStatement(JdbcTemplate.java:454)
5. SELECT * FROM logging_event_exception ORDER BY event_id ASC, i ASC {executed in 1 msec}
date:2016-12-01 13:17:43	thread:main	X-Track:	level:DEBUG	logger:o.s.jdbc.datasource.DataSourceUtils             	message:Returning JDBC Connection to DataSource
```

For reference, the log ran by Tomcat8.5 is below.(The result was succes.) 
```
date:2016-12-01 13:25:42	thread:main	X-Track:	level:DEBUG	logger:o.s.jdbc.datasource.DataSourceTransactionManager	message:Acquired Connection [net.sf.log4jdbc.ConnectionSpy@6401d0a0] for JDBC transaction
date:2016-12-01 13:25:42	thread:main	X-Track:	level:INFO 	logger:o.t.gfw.functionaltest.domain.DBLogCleaner      	message:Begin cleanupAll.
date:2016-12-01 13:25:42	thread:main	X-Track:	level:INFO 	logger:o.t.gfw.functionaltest.domain.DBLogCleaner      	message:Begin cleanup. cutoffDate is 'Thu Dec 01 13:25:42 JST 2016'.
date:2016-12-01 13:25:42	thread:main	X-Track:	level:DEBUG	logger:jdbc.sqltiming                                  	message: org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:688)
1. SELECT MAX(event_id) FROM logging_event WHERE timestmp < 1480566342192 {executed in 48 msec}
date:2016-12-01 13:25:42	thread:main	X-Track:	level:INFO 	logger:jdbc.resultsettable                             	message:|--------------|
date:2016-12-01 13:25:42	thread:main	X-Track:	level:INFO 	logger:jdbc.resultsettable                             	message:|MAX(EVENT_ID) |
date:2016-12-01 13:25:42	thread:main	X-Track:	level:INFO 	logger:jdbc.resultsettable                             	message:|--------------|
date:2016-12-01 13:25:42	thread:main	X-Track:	level:INFO 	logger:jdbc.resultsettable                             	message:|2823          |
date:2016-12-01 13:25:42	thread:main	X-Track:	level:INFO 	logger:jdbc.resultsettable                             	message:|--------------|
date:2016-12-01 13:25:42	thread:main	X-Track:	level:DEBUG	logger:jdbc.sqltiming                                  	message: org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:873)
1. DELETE FROM logging_event_exception WHERE event_id <= 2823 {executed in 1 msec}
date:2016-12-01 13:25:42	thread:main	X-Track:	level:DEBUG	logger:jdbc.sqltiming                                  	message: org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:873)
1. DELETE FROM logging_event_property WHERE event_id <= 2823 {executed in 41 msec}
date:2016-12-01 13:25:43	thread:main	X-Track:	level:DEBUG	logger:jdbc.sqltiming                                  	message: org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:873)
1. DELETE FROM logging_event WHERE event_id <= 2823 {executed in 847 msec}
date:2016-12-01 13:25:43	thread:main	X-Track:	level:INFO 	logger:o.t.gfw.functionaltest.domain.DBLogCleaner      	message:Finished cleanup. Deleted log count is '2823'.
date:2016-12-01 13:25:43	thread:main	X-Track:	level:INFO 	logger:o.t.gfw.functionaltest.domain.DBLogCleaner      	message:Finished cleanupAll.
date:2016-12-01 13:25:43	thread:main	X-Track:	level:DEBUG	logger:o.s.jdbc.datasource.DataSourceTransactionManager	message:Initiating transaction commit
date:2016-12-01 13:25:43	thread:main	X-Track:	level:DEBUG	logger:o.s.jdbc.datasource.DataSourceTransactionManager	message:Committing JDBC transaction on Connection [net.sf.log4jdbc.ConnectionSpy@6401d0a0]
date:2016-12-01 13:25:43	thread:main	X-Track:	level:DEBUG	logger:o.s.jdbc.datasource.DataSourceTransactionManager	message:Releasing JDBC Connection [net.sf.log4jdbc.ConnectionSpy@6401d0a0] after transaction
date:2016-12-01 13:25:43	thread:main	X-Track:	level:DEBUG	logger:o.s.jdbc.datasource.DataSourceUtils             	message:Returning JDBC Connection to DataSource
date:2016-12-01 13:25:44	thread:main	X-Track:	level:DEBUG	logger:o.s.jdbc.datasource.DataSourceUtils             	message:Fetching JDBC Connection from DataSource
date:2016-12-01 13:25:44	thread:main	X-Track:	level:DEBUG	logger:jdbc.sqltiming                                  	message: org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:688)
2. SELECT COUNT(e.*) FROM logging_event e JOIN logging_event_exception ee ON ee.event_id = e.event_id WHERE e.formatted_message REGEXP 'fullwidth must be 1 length string \(fullwidth = \)' AND ee.I = '0' AND ee.TRACE_LINE REGEXP '..*IllegalArgumentException..*' {executed in 1 msec}
date:2016-12-01 13:25:44	thread:main	X-Track:	level:INFO 	logger:jdbc.resultsettable                             	message:|---------|
date:2016-12-01 13:25:44	thread:main	X-Track:	level:INFO 	logger:jdbc.resultsettable                             	message:|COUNT(*) |
date:2016-12-01 13:25:44	thread:main	X-Track:	level:INFO 	logger:jdbc.resultsettable                             	message:|---------|
date:2016-12-01 13:25:44	thread:main	X-Track:	level:INFO 	logger:jdbc.resultsettable                             	message:|1        |
date:2016-12-01 13:25:44	thread:main	X-Track:	level:INFO 	logger:jdbc.resultsettable                             	message:|---------|
date:2016-12-01 13:25:44	thread:main	X-Track:	level:DEBUG	logger:o.s.jdbc.datasource.DataSourceUtils             	message:Returning JDBC Connection to DataSource
```

**Comment by kazuki43zoo** [comment]
Done!
