### ISSUE TITLE
NumberFormatException occurs in maxDisplayCountBlank when started with Weblogic.

### ISSUE THREAD

**Issue by btkatoufm** [terasolunaorg/terasoluna-gfw-functionaltest#924]
## Description
A NumberFormatException occurred in weblogic while testing maxDisplayCountBlank.
I'm trying to convert an empty string to a number.
```
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.valueOf(Integer.java:766)
	at jsp_servlet._web_45_inf._views._pagination.__maxdisplaycountblank._jsp__tag0(__maxdisplaycountblank.java:166)
	at jsp_servlet._web_45_inf._views._pagination.__maxdisplaycountblank._jspService(__maxdisplaycountblank.java:128)
	at weblogic.servlet.jsp.JspBase.service(JspBase.java:35)
	...
```
In addition, it works normally on tomcat.
Consider modifying it so that the behavior does not change for each server used.

## Possible Solution
I think you need to handle the type conversion yourself, without depending on the server.

## Affect versions
- 5.6.1.RELEASE

## Issue links

- #xx

**Comment by btkatoufm** [comment]
As a temporary measure, I will leave it as `@Ignore`, but let's solve it as soon as possible.

**Comment by yoshikawaa** [comment]
maxDisplayCount is an int type and I think the test that expects to allow blanks is wrong.

Conversely, if the test is positive, then the value received in the String type should be converted to a number so that maxDisplayCount allows blanks.

**Comment by btkatoufm** [comment]
The test item in question is not a functional check of terasoluna-gfw, but simply an operation check of the AP server, so we will not modify terasoluna-gfw but delete the relevant item.
see : https://github.com/terasolunaorg/terasoluna-gfw/issues/1167#issuecomment-1165079921
